# src/main/resources/application.properties
# ??????
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
# ???????????????
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true